<?php
/**
 * Stripe Payment Link configuration for the Donate page.
 *
 * GENERATED by scripts/create-stripe-payment-links.mjs — re-run that script to
 * regenerate. Safe to hand-edit; it only holds public buy.stripe.com URLs.
 *
 * Mode: LIVE
 *
 * Leave a 'url' empty to hide that tier. If EVERY url is empty, the Donate page
 * shows a "coming soon" notice and the Donate nav item / CTA stay hidden.
 *
 * Note: Stripe Payment Links only support customer-chosen ("pay what you want")
 * amounts on ONE-TIME payments, never on recurring ones. That's why there is a
 * 'custom' link for one-time giving but not for monthly.
 *
 * @package CrossroadsCommons
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

return array(

    // One-time gifts — fixed amounts.
    'one_time' => array(
        array( 'amount' => 25,  'label' => '', 'url' => 'https://donate.stripe.com/eVq7sD8hwg7i3AN4qD6sw00' ),
        array( 'amount' => 100, 'label' => '', 'url' => 'https://donate.stripe.com/fZu5kveFU5sE8V77CP6sw02' ),
        array( 'amount' => 500, 'label' => '', 'url' => 'https://donate.stripe.com/00w5kvdBQ08k4ER3mz6sw04' ),
    ),

    // One-time gift of any amount — the donor types the amount on Stripe's page.
    'custom'   => 'https://donate.stripe.com/4gMdR10P48EQ2wJ8GT6sw05',

    // Recurring monthly gifts — fixed amounts only (Stripe limitation).
    'monthly'  => array(
        array( 'amount' => 10,  'label' => '', 'url' => 'https://buy.stripe.com/eVq9ALdBQ9IU0oB7CP6sw06' ),
        array( 'amount' => 25,  'label' => '', 'url' => 'https://buy.stripe.com/3cI8wHcxM5sE2wJf5h6sw07' ),
        array( 'amount' => 50,  'label' => '', 'url' => 'https://buy.stripe.com/00wfZ90P47AM7R30an6sw08' ),
        array( 'amount' => 100, 'label' => '', 'url' => 'https://buy.stripe.com/9B6aEP41g9IU4ER8GT6sw09' ),
        array( 'amount' => 250, 'label' => '', 'url' => 'https://buy.stripe.com/5kQdR19lA8EQefr8GT6sw0a' ),
    ),
);
